### ISSUE TITLE
Menu Interface Design

### ISSUE THREAD

**Issue by lewisainslie** [Facepunch/sbox-boomer#21]
Game Menu

```[tasklist]
### Tasks
- [ ] Main Screen w/ Party View (show people in your party in 3d space, use lobby networking system to network cosmetics to other people and show them) - show last update or something with what is new to the game, maybe show an event that's ongoing if possible, idk
- [ ] Play Screen w/ Matchmaker and Server Browser
- [ ] Matchmaking - Click play, set up settings like map selection, then start searching for a game
- [ ] Options Screen w/ Input Rebinding and Client Settings (so we can remove it from the scoreboard)
- [ ] Stats Screen (see Stats System)
- [ ] Customization menu
```

**Comment by DevulTj** [comment]
**Main Screen References**
![image](https://github.com/Facepunch/sbox-boomer/assets/22372616/4f4e9cfe-6fc2-4495-863d-5b97191d585d)
![image](https://github.com/Facepunch/sbox-boomer/assets/22372616/d14fca47-dc5c-4a34-9e4e-3d77c7acb6ee)
![image](https://github.com/Facepunch/sbox-boomer/assets/22372616/e2ac939e-6f3a-4168-909f-92356e69bdeb)
